# Generated by Django 4.0.3 on 2023-07-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='name',
        ),
    ]
