# Generated by Django 4.0.3 on 2023-07-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
